version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=passWord567
    ports:
      - '1433:1433'
    restart: always
#  redis:
#    image: "redis:latest"
#    ports:
#      - "6379:6379"
