version: '3'
services:
  db:
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    container_name: mysql_host
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: devuser
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci