spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  jackson:
    property-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: true
  messages:
    basename: i18n/Messages
    cache-duration: -1
    encoding: UTF-8
logging:
    net:
      bookmanager:
        infra:
          mapper:
            BookMapper: DEBUG