spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  jackson:
    property-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      springframework: WARN
    net:
      bookmanager:
        infra:
          mapper:
            BookMapper: DEBUG