INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (1, 'アンパンマン', 'アンパンマン', 'やなせたかし', 'ヤナセタカシ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (2, '1リットルの涙', 'イチリットルノナミダ', '木藤亜矢', 'キトウアヤ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (3, 'ONE PIECE1巻', 'ワンピースイッカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (4, 'ONE PIECE2巻', 'ワンピースニカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (5, 'ONE PIECE3巻', 'ワンピースサンカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (6, 'ONE PIECE4巻', 'ワンピースヨンカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (7, 'ONE PIECE5巻', 'ワンピースゴカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (8, 'ONE PIECE6巻', 'ワンピースロッカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (9, 'ONE PIECE7巻', 'ワンピースナナカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (10, 'ONE PIECE8巻', 'ワンピースハチカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (11, 'ONE PIECE9巻', 'ワンピースキュウカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (12, 'ONE PIECE10巻', 'ワンピースジュッカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (13, 'ONE PIECE11巻', 'ワンピースジュウイッカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (14, 'ONE PIECE12巻', 'ワンピースジュウニカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (15, 'ONE PIECE13巻', 'ワンピースジュウサンカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (16, 'ONE PIECE14巻', 'ワンピースジュウヨンカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (17, 'ONE PIECE15巻', 'ワンピースジュウゴカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (18, 'ONE PIECE16巻', 'ワンピースジュウロッカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (19, 'ONE PIECE17巻', 'ワンピースジュウナナカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (20, 'ONE PIECE18巻', 'ワンピースジュウハチカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (21, 'ONE PIECE19巻', 'ワンピースジュウキュウカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (22, 'ONE PIECE20巻', 'ワンピースジュッカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (23, 'ONE PIECE21巻', 'ワンピースニジュウイッカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (24, 'ONE PIECE22巻', 'ワンピースニジュウニカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (25, 'ONE PIECE23巻', 'ワンピースニジュウサンカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')
INSERT INTO book (id, title, kana_title, author, kana_author, release_date) VALUES (26, 'ONE PIECE24巻', 'ワンピースニジュウヨンカン', '尾田栄一郎', 'オダエイイチロウ',　'2020-10-20')

INSERT INTO rental (id, user_id, book_id, rental_date, return_deadline) VALUES (1, 1, 10, '2021-01-01', '2021-01-08')
INSERT INTO rental (id, user_id, book_id, rental_date, return_deadline) VALUES (2, 2, 11, '2021-01-01', '2021-01-08')
INSERT INTO rental (id, user_id, book_id, rental_date, return_deadline) VALUES (3, 3, 12, '2021-01-01', '2021-01-08')
INSERT INTO rental (id, user_id, book_id, rental_date, return_deadline) VALUES (4, 4, 13, '2021-01-01', '2021-01-08')
INSERT INTO rental (id, user_id, book_id, rental_date, return_deadline) VALUES (5, 5, 14, '2021-01-01', '2021-01-08')
