# test自動化パイプライン
name: Test

# mainブランチへのPR作成時に流れる
# チーム開発ならもっといっぱい設定すべきだが、ボッチ開発なのでこれでOK
on:
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  #jobの名前. コレをgithubのBranchProtectionRulesから選ぶ
  kotlin-tests:
      # 実行環境
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        # Runs a set of commands using the runners shell
        - name: run test
          uses: eskatos/gradle-command-action@v1
          with:
            arguments: test